# Numpy Array

#### Convert list to numpy array

In [1]:
import numpy as a

In [2]:
ls = [2,3,4,3,4,5]

In [3]:
numpy_list = a.array(ls)

In [4]:
numpy_list

array([2, 3, 4, 3, 4, 5])

In [5]:
ls

[2, 3, 4, 3, 4, 5]

In [6]:
numpy_list[-3 :]

array([3, 4, 5])

In [7]:
my_matrix = [[1,2,3] , [4,5,6] , [7,8,9]]

In [8]:
np_matrix = a.array(my_matrix)

In [9]:
np_matrix[1][1]

5

### Numpy Method

In [10]:
my_np =  a.arange(1,10,2)

In [11]:
my_np

array([1, 3, 5, 7, 9])

In [12]:
np_matrix.shape

(3, 3)

In [13]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.random.randint(5, size=(2,3))

array([[3, 0, 1],
       [3, 3, 2]])

In [15]:
arr = [1,2,3,4,1,2,3,4]

In [16]:
arr = a.array(arr)

In [17]:
arr.max()

4

In [18]:
arr.min()

1

In [19]:
arr.argmax()

3

In [20]:
arr.argmin()

0

In [21]:
arr.dtype

dtype('int32')

In [22]:
nama = 'fikri'

In [23]:
type(nama)

str

In [24]:
arr

array([1, 2, 3, 4, 1, 2, 3, 4])

In [25]:
arr[0:3]

array([1, 2, 3])

In [26]:
arr[0:4] = 100

In [27]:
arr

array([100, 100, 100, 100,   1,   2,   3,   4])

In [28]:
arr2 = arr.copy()

In [29]:
arr[:] = 1

In [30]:
arr2

array([100, 100, 100, 100,   1,   2,   3,   4])

In [31]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
arr = arr.reshape(2,4)

In [33]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
arr.shape[0]

2

In [41]:
for i in range(len(arr)):
    arr[i] = i 

In [42]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1]])

In [44]:
bool_arr = arr > 0

In [52]:
bool_arr
bool_arr.reshape(1,8).sum()

4

## Numpy Operation

In [53]:
np1 = a.arange(10)
np2 = a.arange(10,20)

In [58]:
print(np1)
print(np2)
print(np2 + np1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]


In [59]:
a.sqrt(np1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])